version: '3.8'

services:
  postgres:
    image: postgres
    container_name: aji_zad4
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ajidb
    ports:
      - '5432:5432'

  pgadmin:
    image: dpage/pgadmin4
    container_name: my-pgadmin-container
    environment:
      PGADMIN_DEFAULT_EMAIL: root@root.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - '5050:80'
    depends_on:
      - postgres